"use client";
import {useEffect,useRef,useState} from "react";
import {Search,Bookmark,SlidersHorizontal,MapPin,ArrowUpRight,RefreshCw,Check,Globe2,BriefcaseBusiness,CircleHelp,Download,Radio,LoaderCircle,ScanSearch,ExternalLink,ShieldCheck} from "lucide-react";
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from "@/components/ui/select";
import {Tabs,TabsList,TabsTrigger} from "@/components/ui/tabs";
import {Switch} from "@/components/ui/switch";
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import type {Preferences,Job,Run} from "@/lib/jobs";
const initial:Preferences={role:"Software engineer",location:"New Zealand",keywords:"",seniority:"intern",visa:"any",remote:false,sources:""};
const presets=[{name:"Software internships",role:"Software engineer",location:"New Zealand",seniority:"intern",keywords:""},{name:"Data & analytics",role:"Data analyst",location:"Australia",seniority:"junior",keywords:"SQL, Python"},{name:"Product design",role:"Product designer",location:"United Kingdom",seniority:"junior",keywords:"Figma"}];
function Picker({id,value,onChange,items}:{id:string;value:string;onChange:(v:string)=>void;items:[string,string][]}){return <Select value={value} onValueChange={onChange}><SelectTrigger id={id} className="picker"><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>}

export default function Home(){
 const [prefs,setPrefs]=useState<Preferences>(initial),[run,setRun]=useState<Run|null>(null),[saved,setSaved]=useState<Job[]>([]),[view,setView]=useState("discover"),[busy,setBusy]=useState(false),[phase,setPhase]=useState(""),[error,setError]=useState(""),[selected,setSelected]=useState<Job|null>(null),[help,setHelp]=useState(false),[filter,setFilter]=useState(""),[sort,setSort]=useState("match"),[auto,setAuto]=useState(false),[ready,setReady]=useState(false),[apiKey,setApiKey]=useState("");
 const abort=useRef<AbortController|null>(null),busyRef=useRef(false);
 useEffect(()=>{try{const p=localStorage.getItem("firstrole-preferences"),s=localStorage.getItem("firstrole-saved"),r=localStorage.getItem("firstrole-last-run"),ak=localStorage.getItem("firstrole-api-key");if(p)setPrefs({...initial,...JSON.parse(p)});if(s)setSaved(JSON.parse(s));if(r)setRun(JSON.parse(r));if(ak)setApiKey(ak);}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("firstrole-preferences",JSON.stringify(prefs))},[prefs,ready]);
 useEffect(()=>{if(ready)localStorage.setItem("firstrole-saved",JSON.stringify(saved))},[saved,ready]);
 useEffect(()=>{if(ready)localStorage.setItem("firstrole-api-key",apiKey)},[apiKey,ready]);
 function update<K extends keyof Preferences>(key:K,value:Preferences[K]){setPrefs(p=>({...p,[key]:value}))}
 async function search(preferences=prefs){if(busyRef.current)return;busyRef.current=true;setBusy(true);setError("");setPhase("Discovering openings across careers pages…");setView("discover");const controller=new AbortController();abort.current=controller;
  try{const response=await fetch("/api/search",{method:"POST",headers:{"Content-Type":"application/json",...(apiKey?{"x-tinyfish-api-key":apiKey}:{})},body:JSON.stringify(preferences),signal:controller.signal});if(!response.ok)throw new Error(((await response.json()) as {error?:string}).error||"Search could not start.");if(!response.body)throw new Error("The search connection did not open.");const reader=response.body.getReader();let pending="",finished=false;const decoder=new TextDecoder();while(true){const {done,value}=await reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});const lines=pending.split("\n");pending=lines.pop()||"";for(const line of lines){if(!line.trim())continue;const event=JSON.parse(line);if(event.type==="progress")setPhase(event.message);if(event.type==="error")throw new Error(event.message);if(event.type==="result"){const result=event.data as Run;setRun(result);localStorage.setItem("firstrole-last-run",JSON.stringify(result));setSaved(old=>old.map(j=>result.jobs.find(n=>n.id===j.id)||j));finished=true}}}if(!finished)throw new Error("Connection ended before completion. Previous results are preserved.");
  }catch(e){setError(e instanceof Error?(e.name==="AbortError"?"Search stopped. Previous results are preserved.":e.message):"Search failed. Please try again.")}finally{setBusy(false);busyRef.current=false;setPhase("")}}
 useEffect(()=>{if(!auto)return;const timer=setInterval(()=>{if(document.visibilityState==="visible"&&!busyRef.current)void search()},30*60*1000);return()=>clearInterval(timer)},[auto,prefs]);
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>void}}).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();try{ctx.registerTool({name:"read_job_results",description:"Read current live job results and the preferences used to find them.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=="object"||Object.keys(input).length)throw new Error("Expected an empty object");return {preferences:run?.preferences,jobs:run?.jobs||[],checkedAt:run?.checkedAt}}},{signal:life.signal})}catch{}return()=>life.abort()},[run]);
 const jobs=(view==="saved"?saved:run?.jobs||[]).filter(j=>`${j.title} ${j.company} ${j.location}`.toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>sort==="company"?a.company.localeCompare(b.company):b.score-a.score);
 const isSaved=(id:string)=>saved.some(j=>j.id===id);
 function toggleSave(job:Job){setSaved(s=>s.some(j=>j.id===job.id)?s.filter(j=>j.id!==job.id):[job,...s])}
 function exportJobs(){const rows=[["Title","Company","Location","Match score","Visa","Salary","Apply URL","Checked at"],...jobs.map(j=>[j.title,j.company,j.location,String(j.score),j.visa,j.salary,j.url,j.checkedAt])];const csv=rows.map(r=>r.map(c=>'"'+(/^[=+@\-]/.test(c)?"'":"")+c.replaceAll('"','""')+'"').join(",")).join("\r\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="firstrole-jobs.csv";a.click();URL.revokeObjectURL(url)}
 const changed=run&&JSON.stringify(run.preferences)!==JSON.stringify(prefs),checked=run?new Date(run.checkedAt).toLocaleString(undefined,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}):null;
 return <div className="app-shell"><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><BriefcaseBusiness size={21}/></span>firstrole<span className="brand-period">.</span></a><span className="top-label">YOUR NEXT CHAPTER</span><div style={{ display: "flex", gap: "8px", alignItems: "center" }}><button className="icon-button" onClick={()=>setHelp(!help)} aria-label="How FirstRole works"><CircleHelp size={21}/></button><a href="https://github.com/Chethan-4255/firstrole_tinyfish.ai" target="_blank" rel="noopener noreferrer" className="icon-button" aria-label="GitHub Repository"><img src="/GitHub_Invertocat_Black.png" width={21} height={21} alt="GitHub" style={{ opacity: 0.7 }} /></a></div></header>
 <div className="workspace"><aside className="preferences"><div className="aside-heading"><SlidersHorizontal size={18}/><h2>Your preferences</h2></div><p className="muted intro-small">A better search starts with you.</p><form onSubmit={e=>{e.preventDefault();void search()}}>
 <label htmlFor="role">What do you want to do?</label><div className="field-icon"><BriefcaseBusiness size={17}/><input id="role" maxLength={100} required value={prefs.role} onChange={e=>update("role",e.target.value)} placeholder="Role or job title"/></div>
 <label htmlFor="location">Where do you want to work?</label><div className="field-icon"><MapPin size={17}/><input id="location" maxLength={100} value={prefs.location} onChange={e=>update("location",e.target.value)} placeholder="City, country, or worldwide"/></div>
 <div className="switch-row"><label htmlFor="remote">Include remote roles</label><Switch id="remote" checked={prefs.remote} onCheckedChange={v=>update("remote",v)}/></div>
 <label htmlFor="seniority">Experience level</label><Picker id="seniority" value={prefs.seniority} onChange={v=>update("seniority",v)} items={[["intern","Internship"],["junior","Graduate / entry level"],["mid","Mid-level"],["senior","Senior"],["any","Any level"]]}/>
 <label htmlFor="keywords">Skills & keywords <span className="optional">optional</span></label><input id="keywords" maxLength={200} value={prefs.keywords} onChange={e=>update("keywords",e.target.value)} placeholder="e.g. Python, React, climate"/><p className="field-note">Separate with commas. Used to rank matches.</p>
 <label htmlFor="visa">Visa sponsorship</label><Picker id="visa" value={prefs.visa} onChange={v=>update("visa",v)} items={[["any","No preference"],["preferred","Prefer sponsorship"],["required","Confirmed sponsorship only"]]}/>
 <details className="source-input"><summary>Add careers pages</summary><label className="sr-only" htmlFor="sources">Careers URLs</label><textarea id="sources" value={prefs.sources} onChange={e=>update("sources",e.target.value)} placeholder={"https://company.com/careers\nOne URL per line (up to 3)"} rows={3} maxLength={1500}/><p className="field-note">Optional. Explore companies you already love.</p></details>
 <details className="source-input"><summary>API Key Settings</summary><label className="sr-only" htmlFor="apiKey">TinyFish API Key</label><input type="password" id="apiKey" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="tf_..." /><p className="field-note">Optional. Uses your local browser storage if provided, otherwise falls back to server configuration.</p></details>
 <button className="primary search-button" type="submit" disabled={busy||!prefs.role.trim()}>{busy?<LoaderCircle className="spin" size={18}/>:<ScanSearch size={18}/>} {busy?"Scouting openings…":"Find my next role"}</button></form><div className="privacy-note"><ShieldCheck size={17}/><p>Preferences and saved jobs stay in this browser. No résumé needed.</p></div><a href="https://www.tinyfish.ai/" target="_blank" rel="noopener noreferrer" className="powered"><span className="tinyfish-mark">≈</span><div>Live web, powered by<br/><strong>TinyFish</strong></div></a></aside>
 <main className="main"><div className="page-heading"><div><div className="eyebrow">LESS SEARCHING. MORE POSSIBILITY.</div><h1>Find your way in<span>.</span></h1><p>Real openings. Clear matches. Your next move.</p></div><div className="heading-art" aria-hidden="true"><span/><span/><span/><BriefcaseBusiness size={34}/></div></div>
 <div className="search-strip"><div><Radio size={18}/><span>{busy?phase:checked?`Last checked ${checked}`:"Ready to explore the live web"}</span></div><div className="refresh-control"><label htmlFor="auto">Refresh every 30 min</label><Switch id="auto" checked={auto} onCheckedChange={setAuto}/></div></div>{auto&&<p className="auto-note">Refreshes while this page is open and visible.</p>}
 {busy&&<div className="progress" role="status"><span className="progress-line"/><p>{phase}</p><button className="text-button" onClick={()=>abort.current?.abort()}>Stop search</button></div>}{error&&<div className="error" role="alert">{error}</div>}{changed&&<div className="notice">Preferences changed. Run a new search to update your matches.</div>}
 {help&&<section className="how-panel"><h2>From the live web to your shortlist</h2><div className="how-grid"><p><b>01 / Discover</b>TinyFish Search finds openings across companies and portals using your preferences.</p><p><b>02 / Read</b>TinyFish Fetch reads live pages and captures evidence for matching.</p><p><b>03 / Explore</b>TinyFish Agent navigates careers boards and opens listings when deeper exploration is needed.</p></div><p className="field-note">Scores measure evidence matching your preferences, not your chance of being hired. Visa support stays unknown unless explicitly stated. An accessible page does not guarantee applications are still open.</p></section>}
 <div className="results-heading"><Tabs value={view} onValueChange={setView}><TabsList variant="line"><TabsTrigger value="discover">Discover <span className="count">{run?.jobs.length||0}</span></TabsTrigger><TabsTrigger value="saved"><Bookmark size={15}/> Shortlist <span className="count">{saved.length}</span></TabsTrigger></TabsList></Tabs><button className="text-button" onClick={exportJobs} disabled={!jobs.length}><Download size={16}/> Export CSV</button></div>
 {(run||view==="saved")&&<div className="result-tools"><div className="field-icon"><Search size={16}/><input aria-label="Filter results" placeholder="Filter by title, company, or location" value={filter} onChange={e=>setFilter(e.target.value)}/></div><Picker id="sort" value={sort} onChange={setSort} items={[["match","Best match"],["company","Company A–Z"]]}/><button className="icon-button" disabled={busy} aria-label="Refresh results" onClick={()=>void search()}><RefreshCw size={18}/></button></div>}
 {run&&view==="discover"&&<div className="run-summary"><span>{run.sources} sources read</span><span>{run.duplicates} duplicates removed</span><span>{run.excluded} irrelevant / closed excluded</span><span>Search {run.calls.search} · Fetch {run.calls.fetch} · Agent {run.calls.agent}</span></div>}
 {!run&&view==="discover"&&!busy?<section className="start-state"><div className="start-icon"><ScanSearch size={30}/></div><h2>Your search, without the tab overload.</h2><p>Set your preferences and we’ll scout live careers pages,<br className="desktop-break"/> read the details, and bring back matches worth your time.</p><div className="preset-list"><span>NEED A STARTING POINT?</span>{presets.map(p=><button key={p.name} onClick={()=>setPrefs({...initial,role:p.role,location:p.location,seniority:p.seniority,keywords:p.keywords})}>{p.name}<ArrowUpRight size={16}/></button>)}</div><div className="trust-strip"><span><Globe2 size={16}/> Multiple live sources</span><span><Check size={16}/> No duplicate listings</span><span><ShieldCheck size={16}/> Evidence, not guesses</span></div></section>:<div className="job-list">{jobs.map(job=><article className="job-card" key={job.id}><div className="company-mark">{job.company.replace(/[^a-z0-9]/gi,"").slice(0,2).toUpperCase()||"JR"}</div><div className="job-content"><div className="job-topline"><span>{job.company}</span><span className="source-badge">{job.source}</span></div><button className="job-title" onClick={()=>setSelected(job)}>{job.title}</button><div className="job-meta"><span><MapPin size={14}/>{job.location}</span><span><BriefcaseBusiness size={14}/>{job.seniority}</span>{job.salary&&<span>{job.salary}</span>}</div><p className="job-summary">{job.summary}</p><div className="job-tags">{job.reasons.slice(0,3).map(r=><span key={r}><Check size={12}/>{r}</span>)}<span className={job.visa==="supported"?"visa-yes":"visa-unknown"}>{job.visa==="supported"?"Sponsorship stated":job.visa==="not-supported"?"No sponsorship":"Visa not stated"}</span></div><div className="job-bottom"><span>{job.method==="agent"?"Browser explored":"Page read"} · {new Date(job.checkedAt).toLocaleDateString()} · {job.status}</span><button className="text-button" onClick={()=>setSelected(job)}>Why this match?</button></div></div><div className="job-actions"><div className="score"><strong>{job.score}</strong><span>match score</span></div><button className={"save-button "+(isSaved(job.id)?"saved":"")} onClick={()=>toggleSave(job)} aria-label={isSaved(job.id)?`Unsave ${job.title}`:`Save ${job.title}`}><Bookmark size={19} fill={isSaved(job.id)?"currentColor":"none"}/></button><a className="apply-link" href={job.url} target="_blank" rel="noopener noreferrer">View & apply<ExternalLink size={14}/></a></div></article>)}{!jobs.length&&!busy&&<section className="empty-results"><Search size={27}/><h2>{view==="saved"?"Keep the possibilities close.":"No verified matches this time."}</h2><p>{view==="saved"?"Save interesting roles to build your shortlist on this device.":"Try a broader location or experience level. Confirmed visa-only searches exclude listings without explicit sponsorship."}</p></section>}</div>}
 {!!run?.warnings?.length&&<details className="warnings"><summary>{run.warnings.length} source notes</summary>{run.warnings.map((w,i)=><p key={i}>{w}</p>)}</details>}<footer><span>Made for your first role. And your next.</span><button onClick={()=>setHelp(true)}>How matching works <CircleHelp size={14}/></button></footer></main></div>
 <Sheet open={!!selected} onOpenChange={o=>{if(!o)setSelected(null)}}><SheetContent className="detail-panel">{selected&&<><SheetHeader><div className="eyebrow">MATCH BREAKDOWN</div><SheetTitle>{selected.title}</SheetTitle><SheetDescription>{selected.company} · {selected.location}</SheetDescription></SheetHeader><div className="detail-score"><strong>{selected.score}</strong> / 100 evidence match</div><h3>What lines up</h3>{selected.reasons.map(r=><p className="reason" key={r}><Check size={16}/>{r}</p>)}{!!selected.gaps.length&&<><h3>What to double-check</h3>{selected.gaps.map(g=><p key={g}>{g}</p>)}</>}<h3>Visa evidence</h3><blockquote>{selected.visaEvidence||"This listing did not explicitly state whether visa sponsorship is available."}</blockquote><h3>From the listing</h3><blockquote>{selected.evidence}</blockquote><p className="field-note">Read {new Date(selected.checkedAt).toLocaleString()}. Check the employer’s requirements before applying.</p><a className="primary" href={selected.url} target="_blank" rel="noopener noreferrer">Open original listing <ExternalLink size={16}/></a></>}</SheetContent></Sheet>
 </div>
}
